package com.project.demo.entity;

import java.io.Serializable;

public class NewsCate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_cate.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_cate.name
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_cate.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_cate
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_cate.id
     *
     * @return the value of news_cate.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_cate.id
     *
     * @param id the value for news_cate.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_cate.name
     *
     * @return the value of news_cate.name
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_cate.name
     *
     * @param name the value for news_cate.name
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_cate.sort
     *
     * @return the value of news_cate.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_cate.sort
     *
     * @param sort the value for news_cate.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}