package com.project.demo.entity;

import java.io.Serializable;
import java.util.Date;

public class News implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.fk_cate_id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Integer fkCateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.title
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.update_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.create_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.cont
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private String cont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.fk_cate_id
     *
     * @return the value of news.fk_cate_id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Integer getFkCateId() {
        return fkCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.fk_cate_id
     *
     * @param fkCateId the value for news.fk_cate_id
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setFkCateId(Integer fkCateId) {
        this.fkCateId = fkCateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.title
     *
     * @return the value of news.title
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.title
     *
     * @param title the value for news.title
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.sort
     *
     * @return the value of news.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.sort
     *
     * @param sort the value for news.sort
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.update_time
     *
     * @return the value of news.update_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.update_time
     *
     * @param updateTime the value for news.update_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.create_time
     *
     * @return the value of news.create_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.create_time
     *
     * @param createTime the value for news.create_time
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.cont
     *
     * @return the value of news.cont
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public String getCont() {
        return cont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.cont
     *
     * @param cont the value for news.cont
     *
     * @mbggenerated Wed Apr 20 13:40:29 CST 2016
     */
    public void setCont(String cont) {
        this.cont = cont == null ? null : cont.trim();
    }
}